'use strict';

/**
 * RC12.1 — Catálogo de eventos e enums do CDS Observability Bus.
 * @module observabilidade/eventTypes
 */

const SCHEMA_VERSION = 'obs.v1';

const CATEGORIAS = Object.freeze({
  PLATFORM: 'platform',
  SECURITY: 'security',
  UX: 'ux',
  PERFORMANCE: 'performance',
  COMERCIAL: 'comercial',
  PAGAMENTO: 'pagamento',
  ESTOQUE: 'estoque',
  FISCAL: 'fiscal',
  CENTRAL: 'central',
  MIIP: 'miip',
  EQUIPAMENTOS: 'equipamentos',
  TEF: 'tef'
});

const NIVEIS = Object.freeze({
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL'
});

const CRITICIDADES = Object.freeze({
  BAIXA: 'baixa',
  MEDIA: 'media',
  ALTA: 'alta',
  CRITICA: 'critica'
});

const RESULTADOS = Object.freeze({
  OK: 'ok',
  ERRO: 'erro',
  TIMEOUT: 'timeout',
  PARCIAL: 'parcial'
});

/** Nomes oficiais suportados pelos adapters RC12.1 */
const EVENT_NAMES = Object.freeze({
  BOOT_STARTED: 'BOOT_STARTED',
  BOOT_DATABASE_READY: 'BOOT_DATABASE_READY',
  BOOT_DATABASE_ERROR: 'BOOT_DATABASE_ERROR',
  BOOT_HTTP_LISTENING: 'BOOT_HTTP_LISTENING',
  BOOT_BACKGROUND_START: 'BOOT_BACKGROUND_START',
  BOOT_BACKGROUND_STEP: 'BOOT_BACKGROUND_STEP',
  BOOT_BACKGROUND_READY: 'BOOT_BACKGROUND_READY',
  BOOT_BACKGROUND_ERROR: 'BOOT_BACKGROUND_ERROR',
  BOOT_MIP_FLAG_READY: 'BOOT_MIP_FLAG_READY',

  LAZY_SERVICE_INIT: 'LAZY_SERVICE_INIT',
  LAZY_SERVICE_CREATED: 'LAZY_SERVICE_CREATED',
  LAZY_SERVICE_REUSED: 'LAZY_SERVICE_REUSED',
  LAZY_SERVICE_ERROR: 'LAZY_SERVICE_ERROR',

  CENTRAL_EVENT: 'CENTRAL_EVENT',
  CENTRAL_SYNC_INICIADA: 'CENTRAL_SYNC_INICIADA',
  CENTRAL_SYNC_CONCLUIDA: 'CENTRAL_SYNC_CONCLUIDA',
  CENTRAL_SYNC_ERRO: 'CENTRAL_SYNC_ERRO',
  CENTRAL_PARSER_CONCLUIDO: 'CENTRAL_PARSER_CONCLUIDO',
  CENTRAL_MIIP_CONCLUIDO: 'CENTRAL_MIIP_CONCLUIDO',
  CENTRAL_DOCUMENTO_RECEBIDO: 'CENTRAL_DOCUMENTO_RECEBIDO',
  CENTRAL_ERRO: 'CENTRAL_ERRO',

  EQUIPMENT_ONLINE: 'EQUIPMENT_ONLINE',
  EQUIPMENT_OFFLINE: 'EQUIPMENT_OFFLINE',
  EQUIPMENT_DISCOVERED: 'EQUIPMENT_DISCOVERED',
  EQUIPMENT_HEALTH_CHANGED: 'EQUIPMENT_HEALTH_CHANGED',
  EQUIPMENT_SYNC_STARTED: 'EQUIPMENT_SYNC_STARTED',
  EQUIPMENT_SYNC_FINISHED: 'EQUIPMENT_SYNC_FINISHED',
  EQUIPMENT_DIAGNOSTIC: 'EQUIPMENT_DIAGNOSTIC',
  HEARTBEAT_FAILED: 'HEARTBEAT_FAILED',
  EQUIPMENT_EVENT: 'EQUIPMENT_EVENT',

  SOAP_INICIADO: 'SOAP_INICIADO',
  SOAP_FINALIZADO: 'SOAP_FINALIZADO',
  SOAP_FALHA: 'SOAP_FALHA',
  SOAP_TIMEOUT: 'SOAP_TIMEOUT',
  SOAP_HTTP_ERROR: 'SOAP_HTTP_ERROR',
  SOAP_CSTAT: 'SOAP_CSTAT',

  MIIP_IDENTIFY_STARTED: 'MIIP_IDENTIFY_STARTED',
  MIIP_IDENTIFY_FINISHED: 'MIIP_IDENTIFY_FINISHED',
  MIIP_HEALTH_DEGRADED: 'MIIP_HEALTH_DEGRADED',

  // RC12.2 — RUM / recursos
  AUTH_LOGIN_DURATION: 'AUTH_LOGIN_DURATION',
  MODULE_OPEN: 'MODULE_OPEN',
  MODULE_LAZY_CREATED: 'MODULE_LAZY_CREATED',
  MODULE_LAZY_REUSED: 'MODULE_LAZY_REUSED',
  MODULE_LAZY_ERROR: 'MODULE_LAZY_ERROR',
  RESOURCE_SAMPLE: 'RESOURCE_SAMPLE'
});

module.exports = {
  SCHEMA_VERSION,
  CATEGORIAS,
  NIVEIS,
  CRITICIDADES,
  RESULTADOS,
  EVENT_NAMES
};
