/**
 * Tipos de eventos da Central de Entradas (Sprint 8).
 *
 * @module motores/central-entradas/config/centralEventosTipos
 */

const TIPOS_EVENTO = Object.freeze({
  SYNC_INICIADA: 'SYNC_INICIADA',
  SYNC_CONCLUIDA: 'SYNC_CONCLUIDA',
  SYNC_ERRO: 'SYNC_ERRO',
  DOCUMENTO_RECEBIDO: 'DOCUMENTO_RECEBIDO',
  DOCUMENTO_PROCESSADO: 'DOCUMENTO_PROCESSADO',
  DOCUMENTO_ATUALIZADO: 'DOCUMENTO_ATUALIZADO',
  DOCUMENTO_MIGRADO: 'DOCUMENTO_MIGRADO',
  CIENCIA_ENVIADA: 'CIENCIA_ENVIADA',
  /** Claim atômico pré-envio (RC3.3.3) — não é evento de timeline de negócio. */
  MANIFESTACAO_CLAIM: 'MANIFESTACAO_CLAIM',
  MANIFESTACAO_ACEITA: 'MANIFESTACAO_ACEITA',
  MANIFESTACAO_REJEITADA: 'MANIFESTACAO_REJEITADA',
  CONSULTA_DFE_POS_MANIFESTACAO: 'CONSULTA_DFE_POS_MANIFESTACAO',
  PARSER_CONCLUIDO: 'PARSER_CONCLUIDO',
  /** RC3.4.9 — importação manual de XML legado (Portal Nacional). */
  XML_IMPORTADO_MANUALMENTE: 'XML_IMPORTADO_MANUALMENTE',
  XML_VALIDADO: 'XML_VALIDADO',
  XML_REJEITADO: 'XML_REJEITADO',
  PARSER_INICIADO: 'PARSER_INICIADO',
  PARSER_FINALIZADO: 'PARSER_FINALIZADO',
  /** RC3.5.0 — Portal Nacional da NF-e */
  PORTAL_ABERTO: 'PORTAL_ABERTO',
  /** RC3.5.1 — chave enviada ao Portal (preenchimento automático). */
  CHAVE_ENVIADA: 'CHAVE_ENVIADA',
  /** RC3.6.1 — chave copiada para área de transferência (CTRL+V). */
  CHAVE_COPIADA_AUTOMATICAMENTE: 'CHAVE_COPIADA_AUTOMATICAMENTE',
  /** RC3.6.H — usuário copiou chave manualmente (ação independente do Portal). */
  CHAVE_COPIADA: 'CHAVE_COPIADA',
  /** RC3.6.0 — Central de Recuperação CDS */
  CENTRAL_RECUPERACAO_ABERTA: 'CENTRAL_RECUPERACAO_ABERTA',
  PORTAL_CONSULTA_INICIADA: 'PORTAL_CONSULTA_INICIADA',
  DOWNLOAD_DETECTADO: 'DOWNLOAD_DETECTADO',
  DOCUMENTO_RECUPERADO: 'DOCUMENTO_RECUPERADO',
  /** RC3.6.1 — Assistente de Recuperação CDS */
  RECUPERACAO_INICIADA: 'RECUPERACAO_INICIADA',
  IMPORTACAO_INICIADA: 'IMPORTACAO_INICIADA',
  RECUPERACAO_FINALIZADA: 'RECUPERACAO_FINALIZADA',
  DOWNLOAD_INICIADO: 'DOWNLOAD_INICIADO',
  DOWNLOAD_CONCLUIDO: 'DOWNLOAD_CONCLUIDO',
  DOWNLOAD_CANCELADO: 'DOWNLOAD_CANCELADO',
  DOWNLOAD_ERRO: 'DOWNLOAD_ERRO',
  PIPELINE_INICIADO: 'PIPELINE_INICIADO',
  MIIP_INICIADO: 'MIIP_INICIADO',
  MIIP_FINALIZADO: 'MIIP_FINALIZADO',
  DOCUMENTO_RECUPERADO_PORTAL: 'DOCUMENTO_RECUPERADO_PORTAL',
  MIIP_CONCLUIDO: 'MIIP_CONCLUIDO',
  COMPRA_GRAVADA: 'COMPRA_GRAVADA',
  COMPRA_CRIADA: 'COMPRA_CRIADA',
  ERRO: 'ERRO',
  CONFIG_ALTERADA: 'CONFIG_ALTERADA',
  /** RC3.7.5 — Motor de recuperação automática de XML */
  RECUPERACAO_XML_ENTROU_FILA: 'RECUPERACAO_XML_ENTROU_FILA',
  RECUPERACAO_XML_CONSULTA: 'RECUPERACAO_XML_CONSULTA',
  RECUPERACAO_XML_RECUPERADO: 'RECUPERACAO_XML_RECUPERADO',
  RECUPERACAO_XML_FALHA: 'RECUPERACAO_XML_FALHA',
  RECUPERACAO_XML_TIMEOUT: 'RECUPERACAO_XML_TIMEOUT',
  RECUPERACAO_XML_REMOVIDO: 'RECUPERACAO_XML_REMOVIDO',
  /** RC3.7.5.1 — cursor NSU sincronizado automaticamente após cStat 656 */
  AUTO_SYNC_NSU: 'AUTO_SYNC_NSU',
  /** RC3.7.5.2 — NSU obtido via fallback XML (namespace) */
  NSU_RECOVERED_FROM_XML: 'NSU_RECOVERED_FROM_XML'
});

const ORIGENS = Object.freeze({
  BACKGROUND: 'background',
  MANUAL: 'manual',
  API: 'api',
  SISTEMA: 'sistema',
  ABRIR_CENTRAL: 'abrir_central',
  DIAGNOSTICO: 'diagnostico',
  UPLOAD: 'upload',
  COMPRAS: 'compras',
  MIGRACAO_RC65: 'MIGRACAO_RC65',
  /** RC3.4.9 — módulo oficial Importação de XML Legado. */
  IMPORTACAO_MANUAL: 'importacao_manual',
  /** RC3.5.0 — recuperação via Portal Nacional. */
  PORTAL_NACIONAL: 'portal_nacional',
  /** RC3.7.5 — recuperação automática DistDFe/consChNFe */
  RECUPERACAO_XML: 'recuperacao_xml_automatica'
});

module.exports = {
  TIPOS_EVENTO,
  ORIGENS
};
